# Generated by Django 6.1.1 on 2026-09-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledoutput',
            name='command_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledoutput',
            name='command_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledoutput',
            name='latency_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
