# Generated by Django 6.1.1 on 2026-09-25 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_ledoutput_command_applied_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='device',
        ),
        migrations.CreateModel(
            name='DeviceChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('direction', models.CharField(choices=[('output', 'Output'), ('input', 'Input')], max_length=10)),
                ('signal_type', models.CharField(choices=[('digital', 'Digital'), ('analog', 'Analog')], max_length=10)),
                ('state', models.FloatField(default=0)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('command_issued_at', models.DateTimeField(blank=True, null=True)),
                ('command_applied_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.devicechannel')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='LEDOutput',
        ),
        migrations.DeleteModel(
            name='SensorReading',
        ),
    ]
