# Generated by Django 6.1.1 on 2026-09-25 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_sensorreading_device_devicechannel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reference_image', models.ImageField(upload_to='known_faces/')),
                ('face_encoding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='door_events/')),
                ('is_known', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_events', to='devices.device')),
                ('matched_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.knownperson')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
