# Generated by Django 6.1.1 on 2026-09-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_knownperson_doorevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='unlock_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='devices.devicechannel'),
        ),
    ]
