# Generated by Django 6.1.1 on 2026-09-28 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_unlock_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knownperson',
            name='face_encoding',
        ),
        migrations.RemoveField(
            model_name='knownperson',
            name='reference_image',
        ),
        migrations.CreateModel(
            name='FaceSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='known_faces/')),
                ('face_encoding', models.JSONField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='devices.knownperson')),
            ],
        ),
    ]
