# Generated by Django 6.1.1 on 2026-09-28 09:26

import devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_remove_knownperson_face_encoding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facesample',
            name='image',
            field=models.ImageField(upload_to=devices.models.face_sample_path),
        ),
    ]
